const electron = require('electron')
const { app, BrowserWindow } = require('electron')
var os = require('os')

app.on('ready', () => {
	var fs = require('fs');

	

	let win = new BrowserWindow({ width: 800, height: 600, icon: __dirname + '/../assets/WhatsApp-icon.png' })
	win.loadURL('https://web.whatsapp.com')
	let content = win.webContents

	if (os.platform() !== 'darwin') {
		win.setMenu(null);
	}

	win.webContents.on('did-finish-load', function () {
		win.webContents.insertCSS(css)
	})

	app.on('window-all-closed', app.quit);
	app.on('before-quit', () => {
		win.removeAllListeners('close');
		win.close();
	})

	var css = [
	":root {",
	"  --bgn: #272C35; /* main bg color */",
	"  --bgd: #1F232A; /* darker highlight color */",
	"  --bgh: #3C4149; /* lighter highlight color */",
	"  --bgt: #B6BABF; /* faded text color */",
	"  --bgo: #E9F4FE; /* text color */",
	"  --bga: #7289DA; /* accent color */",
	"  --bgi: url(https://images.discordapp.net/attachments/310799529161129984/320568157142122496/zilesana.jpg?width=1920&height=1080) !important; /* bg image */ ",
	"",
	"  /* Group colors. */",
	"  --bg1: #CA3269;",
	"  --bg2: #945432;",
	"  --bg3: #1ABD5C;",
	"  --bg4: #6E54FE;",
	"  --bg5: #005685;",
	"  --bg6: #E08513;",
	"  --bg7: #2049EF;",
	"  --bg8: #FD62FF;",
	"  --bg9: #748522;",
	"  --bg10: #018380;",
	"  --bg11: #45CC23;",
	"  --bg12: #A62C97;",
	"  --bg13: #4FB9CD;",
	"  --bg14: #027A2B;",
	"  --bg15: #7C6C35;",
	"  --bg16: #0070D3;",
	"  --bg17: #7C4D67;",
	"  --bg18: #4B7891;",
	"  --bg19: #36DC86;",
	"  --bg20: #10B4B0;",
	"}",
	"",
	"/* preloader */",
	"#startup, #initial_startup { background-color: var(--bgn) !important; }",
	"",
	"/* login page (XD) */",
	"#wrapper {",
	"  background-color: transparent !important;",
	"  background-image: none !important; }",
	"  /* accent background */",
	"  #wrapper::before {",
	"    display: none !important; }",
	"    /* modal */",
	"    #window, #platforms {",
	"      background-color: var(--bgn) !important; }",
	"  /* qr code fix */",
	"  .qrcode { border: 1px solid var(--bgt) !important; }",
	"  /* modal text */",
	"  #window .entry-main .entry-text div, #platforms ul li {",
	"    color: var(--bgt) !important; }",
	"",
	"/* inverted icons */",
	"  .qrcode .icon, .entry-platform .icon, .audio-status.icon { filter: invert(0%) !important; }",
	"",
	"/* notification button */",
	".butterbar, .butterbar > div > div {",
	"  background-color: var(--bgh) !important;",
	"  color: var(--bgt) !important; }",
	"",
	"/* startup intro thing */",
	".intro {",
	"	box-shadow: 1px -3px 2px 0 rgba(0, 0, 0, 0.3) inset !important;",
	"  background-color: var(--bgn) !important;",
	"  border-left: none !important; }",
	"  /* title fix */",
	"  .intro-title {",
	"    color: var(--bgt) !important; }",
	"	/* divider. xd */",
	"	.intro-divider { background-color: var(--bgd) !important; }",
	"	/* intro image */",
	"	.intro-image {",
	"	  width: 250px !important;",
	"	  height: 250px !important;",
	"	  border-radius: 50% !important;",
	"	  opacity: 0.66 !important;",
	"	  background-size: cover !important; }",
	"",
	"/* small bg-image fix */",
	"#app {",
	"  background-image: none !important;",
	"  background-color: var(--bgn) !important;",
	"  z-index: 1 !important; /* quick fix to show the bg image */ }",
	"",
	"/* another app element. Â¯\\_(ã)_/Â¯ */",
	".app { background: none !important; }",
	"",
	"/* background image */",
	".app-wrapper::after {",
	"  z-index: -1;",
	"  width: calc(100% + 20px) !important;",
	"  height: calc(100% + 20px) !important;",
	"  top: -10px !important;",
	"  left: -10px !important;",
	"  background-color: var(--bgh) !important;",
	"",
	"  background-image: var(--bgi) !important;",
	"/*   background-image: url(\'https://unsplash.it/1920/1080/?randomz\') !important; */",
	"/*   background-image: url(\'https://images.unsplash.com/15/leaf.JPG\') !important; */",
	"",
	"  filter: blur(5px) hue-rotate(0deg) grayscale(0%) opacity(40%) !important;",
	"",
	"  background-size: cover !important;",
	"  background-position: center !important;",
	"  background-repeat: no-repeat !important; }",
	"",
	"/* inverted icons */",
	".icon, .context-icon, .icon-star-in, .btn-star, .btn-delete, .btn-forward {",
	"	filter: invert(100%) grayscale(100%) !important; }",
	"",
	"/* re-inverted icons ._. */",
	".icon-alert.icon-alert-notification, .icon-search-morph, .btn-close-drawer, .icon-back-light, .icon-x-alt, .icon-chevron-right-alt, .icon-emoji-gifs, .icon-send-light, .icon-forward-chat, .icon-menu-white, .list-action-icon .icon, .icon-msg-dblcheck, .icon-pinned, .icon-camera-light { filter: invert(0%) !important; }",
	"",
	"/* grid */",
	"#side > * { background-color: var(--bgd) !important; }",
	"",
	"/* header styles */",
	"#side > header {",
	"  padding: 0 10px !important;",
	"  height: 60px !important; }",
	"",
	"/* chat box shadow */",
	"#main {",
	"	box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.333) !important; }",
	"",
	"/* active menu */",
	".dropdown { background-color: var(--bgh) !important; }",
	"  /* dropdown item links */",
	"  .menu-item a { color: var(--bgt) !important; }",
	"    /* hovering over dropdown item */",
	"    .menu-item a:hover { background-color: var(--bgd) !important; }",
	"    /* quick fix for the circle icons */",
	"    .menu.menu-icons ul li:hover { border-radius: 50% !important; }",
	"",
	"",
	"/* search container */",
	".subheader-search, .subheader-search label { background-color: var(--bgd) !important; }",
	"",
	"/* search or start new chat */",
	".subheader-search.active label, .cont-input-search, .chatlist-panel-search, .drawer .chatlist {",
	"  border: 0px solid transparent !important;",
	"  background-color: var(--bgh) !important; }",
	"  /* input element */",
	"  .cont-input-search input {",
	"    background-color: transparent !important;",
	"    color: var(--bgt) !important; }",
	"  /* active */",
	"  .subheader-search.active {",
	"    box-shadow: 0px 2px 3px rgba(0,0,0,0.07);",
	"    box-shadow: none !important; }",
	"  /* chat items */",
	"  .infinite-list-item .list-title {",
	"    background-color: var(--bgh) !important; }",
	"  .infinite-list .section-header {",
	"  	background-color: var(--bgd) !important; }",
	"",
	"/* drawer menu\'s and stuff */",
	".drawer { background-color: var(--bgd) !important; }",
	".drawer-header, .drawer header, .menu-tabs.menu-tabs-lists { background-color: var(--bgh) !important; }",
	".drawer-body { background-color: var(--bgd) !important; margin-bottom: 0px !important; /* TWEAK */ }",
	"/* gaps on the sides. */",
	".drawer-info .drawer-section { margin: 10px 10px 0px !important; }",
	"",
	"/* alternative colored elements */",
	".well, .well-simple, .well-chat, .multi-vcard-dialog-contact, .list-action {",
	"  background-color: var(--bgh) !important;",
	"  box-shadow: 0 1px 3px rgba(0,0,0,0.08); }",
	"",
	"/* text */",
	".text-input, .drawer-title-body, .chat-title, .chat-secondary, .header-title, .well-chat-name, .title, .starred-title-main, .starred-title-meta, .meta .hidden-token, .text-input .label-text, .chat-status, .media-content .media-caption, .list-action, body, select, .inputarea, .chat.member .chat-body *, .chat.member .header-body * { color: var(--bgt) !important; }",
	"",
	"/* starred messages */",
	".starred-msg-wrapper {",
	"  transition: 200ms ease-in-out !important; }",
	"  /* trigger */",
	"  .starred-msg-wrapper.hover, .starred-msg-wrapper.current {",
	"    background-color: var(--bgn) !important; }",
	"",
	"/* unread message */",
	".unread-count { background-color: var(--bgh) !important; }",
	"",
	"/* chat list styles */",
	".chat { background-color: var(--bgn) !important; }",
	".chat:hover { background-color: var(--bgh) !important; }",
	".chat .chat-body { border: none !important; }",
	".chat .chat-body * { color: var(--bgt) !important; }",
	"",
	"/* weird things. */",
	".chatlist .chat:hover::after, .chatlist .chat.hover::after, .chatlist .chat.active::after, .row-drawer-item .row-body, .list-action, .list-action-alt .list-action-body {",
	"  border-bottom: 0px solid transparent !important; }",
	".pane-chat-header::after, .subheader-search::after, .starred-msg-wrapper::before, .starred-msg-wrapper.hover::before, .starred-msg-wrapper.hover::after, select, .starred-msg-wrapper.current::before, .starred-msg-wrapper.current::after {",
	"  background-color: transparent !important;",
	"  border-bottom: 0px solid transparent !important; }",
	".pane-chat-header::after, .list-search::after {",
	"	display: none !important; }",
	"",
	"/* haHAA very funny. */",
	".three .pane-chat-body, .three .pane-chat-footer { border: none !important; }",
	"",
	"/* chat drawer */",
	"#main.pane-chat { background-color: var(--bgn) !important; }",
	"  /* chat title */",
	"  header.pane-chat-header, .pane-three {",
	"    border-left: 0px solid transparent !important;",
	"    background-color: var(--bgn) !important;  }",
	"  /* chat input */",
	"  .pane-chat-footer {",
	"    background-color: var(--bgn) !important;",
	"    border-left: 0px solid transparent !important; }",
	"    /* child element */",
	"    .block-compose { background-color: transparent !important; }",
	"      /* text input element */",
	"      .block-compose .input-container {",
	"        background-color: var(--bgh) !important;",
	"        border: 0px solid transparent !important;",
	"        box-shadow: inset 0 0 2px 0 rgba(0,0,0,0.33), 0 0 6px 0 rgba(0,0,0,0.1) !important;",
	"        color: var(--bgt) !important; /* text color fix */ }",
	"      /* reply. (: */",
	"      .compose-popup-panel { background-color: var(--bgn) !important; }",
	"        /* message content */",
	"        .compose-popup-panel .quoted-msg-status { background-color: var(--bgh) !important; }",
	"        /* close reply button */",
	"        .btn-background { background-color: var(--bgh) !important; }",
	"    /* mentions */",
	"  .mentions-positioning-container div {",
	"    background: var(--bgh) !important; }",
	"",
	"/* message info */",
	".pane-preview, .pane-preview .pane-chat-tile { background: var(--bgh) !important; }",
	"",
	"/* bold message */",
	".message-text strong, .media-caption strong {",
	"  color: var(--bgo) !important;",
	"  text-shadow: none !important; }",
	"",
	"/* day/time message*/",
	".message-system-body {",
	"  color: var(--bgo) !important;",
	"  text-shadow: none !important;",
	"  background-color: var(--bgh) !important;",
	"  box-shadow: 0 1px 0.5px rgba(0, 0, 0, 0.13) !important; }",
	"",
	"/* button more */",
	".btn-more { background-color: var(--bgh) !important; }",
	"",
	"/* new message indicator */",
	".msg-unread {",
	"  border: none !important;",
	"  background-color: var(--bgd) !important; }",
	"  /* body element */",
	"  .msg-unread-body {",
	"    background-color: var(--bgh) !important;",
	"    color: var(--bgt) !important; }",
	"",
	"",
	"/* bubble in */",
	".message-in, .message-out {",
	"  background-color: var(--bgh) !important;",
	"  border-radius: 5px !important; }",
	"  /* bubble tails */",
	"  .tail-container { display: none !important; }",
	"  /* bubbles text */",
	"  .message-text, .message-meta, .document-meta-value { color: var(--bgt) !important; }",
	"  /* message menu */",
	"  .context { background: var(--bgh) !important; }",
	"  /* message sent fix */",
	"  .icon.icon-msg-dblcheck-ack, .icon.icon-status-dblcheck-ack, .icon.icon-msg-dblcheck, .icon-msg-dblcheck-light { filter: invert(0%) !important; }",
	"",
	"/* chat section bg */",
	".pane-chat-tile { filter: invert(80%) !important; }",
	"",
	"",
	"/* emoji menu lel */",
	".emoji-panel-body-container, .emoji-search-row, .emoji-search, .dropdown-picker, .dropdown-picker .nib { background: var(--bgn) !important; }",
	"  /* emoji tabs */",
	"  .emoji-panel-header { background: var(--bgd) !important; }",
	"  /* emoji search */",
	"  .emoji-search-row-input { background-color: var(--bgh) !important; }",
	"    /* input text color fix*/",
	"    .emoji-search-row-input input { color: var(--bgt) !important; }",
	"  /* inverted menu icons */",
	"  .menu-tab { filter: invert(100%) !important; }",
	"  /* gif default bg */",
	"  .gif-search-gif-wrapper { background-color: var(--bgh) !important; }",
	"  /* add media button*/",
	"  .btn-fill { background-color: var(--bgn) !important; }",
	"",
	"",
	"/* incoming messages */",
	".incoming-msgs { background-color: var(--bgh) !important; }",
	"",
	"",
	"/* select messages (WHY WOULD YOU EVER DO THAT?!) */",
	".pane-chat-body.selectable { background-color: rgba(255, 255, 255, 0.2) !important; }",
	"  /* selected message */",
	"  .selected .msg-select {",
	"    background-color: rgba(39, 44, 53, 0.25) !important; }",
	"    /* voodoo magic */",
	"    .msg-select:hover { background-color: rgba(39, 44, 53, 0.25) !important; }",
	"  /* footer */",
	"  .multi-controls { background-color: var(--bgd) !important; }",
	"",
	"",
	"/* photo plz */",
	".media-body-container-background { background-color: var(--bgn) !important; }",
	"  /* avatar zoom in/out */",
	"  .avatar-picker-controls { background-color: var(--bgh) !important; }",
	"  /* footer */",
	"  .drawer-edit .capture-footer { background-color: var(--bgd) !important; }",
	"",
	"",
	"/* new group wrapper */",
	".new-group-contacts, .drawer-section-main { background-color: var(--bgd) !important;}",
	"  /* search */",
	"  .new-group-search, .list-search.active { background-color: var(--bgh) !important; }",
	"    /* search element ._. */",
	"    .input-line {",
	"      color: var(--bgt) !important;",
	"      border-bottom: 1px solid rgba(0, 0, 0, 0) !important; }",
	"  /* system message */",
	"  .message-system {",
	"    color: var(--bgt) !important;",
	"    text-shadow: none !important;",
	"    background-color: var(--bgh) !important; }",
	"",
	"",
	"/* media viewer */",
	".media-viewer {",
	"  background-color: rgba(39,44,53,0.90) !important; }",
	"  /* media viewer header */",
	"  .media-panel-header, .chat.media-chat {",
	"    background-color: var(--bgh) !important; }",
	"  /* media viewer footer */",
	"  .media-collection {",
	"    background-color: var(--bgh) !important;",
	"    border: none !important; }",
	"  /* media, links, docs */",
	"  .media-canvas { outline: none !important; }",
	"",
	"",
	"/* modal */",
	".backdrop { background-color: rgba(25, 25, 35, 0.85); }",
	"  /* modal element */",
	"  .popup { background-color: var(--bgn) !important; }",
	"    /* modal text */",
	"    .popup-title, .popup-contents { color: var(--bgt) !important; }",
	"    /* separator fix */",
	"    .popup hr { border-top: 1px solid rgba(0, 0, 0, 0) !important; }",
	"  /* transparent pop-up. ¯\\_(ツ)_/¯ */",
	"  .backdrop-transparent { background: transparent !important; }",
	"",
	"",
	"/* custom text code thing doodle. */",
	"/*.input-placeholder {",
	"  color: transparent !important;",
	"  width:  100% !important; }*/",
	"  /* magic-moomoo! */",
	"  /*.input-emoji .input-placeholder::before {",
	"    content: \'∞\' !important;",
	"    color: var(--bgt) !important;",
	"    text-align: center !important;",
	"    position: absolute !important;",
	"    width: 100% !important; }*/",
	"",
	"/* J\'s requested feature */",
	" .chatlist > div > .infinite-list-item { filter: blur(10px); transition: 200ms ease-in-out; }",
	" .chatlist > div > .infinite-list-item:hover { filter: blur(0px); }",
	"",
	"/* easter egg(?) */",
	"/*.app-wrapper::before {",
	"  z-index: 999 !important;",
	"  position: absolute !important;",
	"  top: 0 !important;",
	"  left: 0 !important;",
	"  width: 100% !important;",
	"  content: \'•-•\' !important;",
	"  color: rgba(255, 255, 255, 0.333) !important;",
	"  font-size: 24px !important;",
	"  line-height: 19px !important;",
	"  text-align: center !important; }*/",
	"",
	"/* THE ONE PROBE */",
	"/* *:hover { border: 1px dotted crimson !important; } */",
	"",
	"",
	"/* I should organize code properly and make it more modular. Next update, I promise. */",
	"",
	"/* search message body */",
	".chatlist-panel-body {",
	"  background-color: var(--bgd) !important; }",
	"",
	"",
	"/* Link preview bubble */",
	".link-preview-container {",
	"  color: var(--bgt) !important;",
	"  background-color: var(--bgn) !important; }",
	"  /* Link preview bubble text elements */",
	"  .link-preview-title, .link-preview-description, .link-preview-source {",
	"      color: var(--bgt) !important; }",
	"  /* Link preview bubble tail */",
	"  .context-special.context-out {",
	"    background: var(--bgn) !important; }",
	"",
	"/* drop items (-: */",
	".drag-drop {",
	"  background-color: var(--bgh) !important; }",
	"  /* \'stitching\' */",
	"  .drag-drop .stitching {",
	"    border: 5px dashed var(--bgd) !important;",
	"    color: var(--bgt) !important; }",
	"",
	"/* documents */",
	".document-body {",
	"  color: var(--bgt) !important;",
	"  background-color: var(--bgn) !important; }",
	"",
	"",
	"/* Version 1.0.7 - A *somewhat* messy update. */",
	"",
	"",
	"/* Login -- QR page. */",
	".qr-wrapper, .qr-wrapper::before {",
	"  background: none !important; }",
	"  .qr-window {",
	"    background-color: var(--bgn) !important; }",
	"  .qr-platforms {",
	"    background-color: var(--bgn) !important; }",
	"    .qr-platforms ul li, .entry-text > div  {",
	"      color: var(--bgt) !important; }",
	"",
	"/* White borders. */",
	".chat.active::after, .chat.hover::after, .chatlist.list-icons .chat:hover::after, .contact::after, .chat::after {",
	"  border-color: transparent !important; }",
	"",
	"/* Darkened elements. */",
	".chat.active, .chat.hover, .dropdown-item-hover, .status-v3-modal-background, .backdrop.backdrop-cover {",
	"  background-color: var(--bgd) !important; }",
	"",
	"/* Icon colors. */",
	".icon-pinned, .btn-context {",
	"  filter: invert(100%) !important; }",
	"",
	"/* Text color. */",
	".chat-subtitle-text, .dropdown .dropdown-items li div, .hidden-token {",
	"  color: var(--bgt) !important; }",
	"",
	"/* Chat color instaed of the image, got plans for this. */",
	".pane-chat-tile {",
	"  background: none !important; }",
	"",
	"/* Button colors. */",
	".btn {",
	"  background-color: var(--bga) !important; }",
	".btn-fill {",
	"  color: var(--bga) !important; }",
	".btn-default {",
	"  background-color: var(--bga) !important;",
	"  color: var(--bgo) !important; }",
	"",
	"/* Border color beneath input elements. */",
	".text-input-active, .input-wrapper {",
	"  border-bottom: 2px solid var(--bga) !important; }",
	"",
	"/* Admin color. */",
	".contact-marker-admin {",
	"  border: 1px solid var(--bga) !important; }",
	"",
	"/* Unreadable popup text. */",
	".textfield-static {",
	"  color: var(--bgo) !important; }",
	"",
	"/* Gray loading icon. */",
	".spinner-container, .icon-audio-file {",
	"  filter: grayscale(1) !important; }",
	"",
	"/* Accent text color. */",
	".row-main, .row-side {",
	"  color: var(--bga) !important; }",
	"",
	"/* loading icon background when scrolling up fix */",
	".more-messages, .pane-chat-empty {",
	"  background-color: var(--bgd) !important; }",
	"",
	".infinite-list-item-transition {",
	"  background-color: var(--bgn) !important; }",
	"",
	"/* Input bar. */",
	".input-emoji .input:focus {",
	"  background: var(--bgh) !important; }",
	"",
	"/* Colors in groups. */",
	".color-1 { color: var(--bg1) !important; }",
	".color-2 { color: var(--bg2) !important; }",
	".color-3 { color: var(--bg3) !important; }",
	".color-4 { color: var(--bg4) !important; }",
	".color-5 { color: var(--bg5) !important; }",
	".color-6 { color: var(--bg6) !important; }",
	".color-7 { color: var(--bg7) !important; }",
	".color-8 { color: var(--bg8) !important; }",
	".color-9 { color: var(--bg9) !important; }",
	".color-10 { color: var(--bg10) !important; }",
	".color-11 { color: var(--bg11) !important; }",
	".color-12 { color: var(--bg12) !important; }",
	".color-13 { color: var(--bg13) !important; }",
	".color-14 { color: var(--bg14) !important; }",
	".color-15 { color: var(--bg15) !important; }",
	".color-16 { color: var(--bg16) !important; }",
	".color-17 { color: var(--bg17) !important; }",
	".color-18 { color: var(--bg18) !important; }",
	".color-19 { color: var(--bg19) !important; }",
	".color-20 { color: var(--bg20) !important }",
	".bg-color-1 { background-color: var(--bg1) !important; }",
	".bg-color-2 { background-color: var(--bg2) !important; }",
	".bg-color-3 { background-color: var(--bg3) !important; }",
	".bg-color-4 { background-color: var(--bg4) !important; }",
	".bg-color-5 { background-color: var(--bg5) !important; }",
	".bg-color-6 { background-color: var(--bg6) !important; }",
	".bg-color-7 { background-color: var(--bg7) !important; }",
	".bg-color-8 { background-color: var(--bg8) !important; }",
	".bg-color-9 { background-color: var(--bg9) !important; }",
	".bg-color-10 { background-color: var(--bg10) !important; }",
	".bg-color-11 { background-color: var(--bg11) !important; }",
	".bg-color-12 { background-color: var(--bg12) !important; }",
	".bg-color-13 { background-color: var(--bg13) !important; }",
	".bg-color-14 { background-color: var(--bg14) !important; }",
	".bg-color-15 { background-color: var(--bg15) !important; }",
	".bg-color-16 { background-color: var(--bg16) !important; }",
	".bg-color-17 { background-color: var(--bg17) !important; }",
	".bg-color-18 { background-color: var(--bg18) !important; }",
	".bg-color-19 { background-color: var(--bg19) !important; }",
	".bg-color-20 { background-color: var(--bg20) !important; }"
].join("\n")
})
